config/routes.rb
Rails.application.routes.draw do

  root 'users#index'

  get 'categories/new' => 'categories#new', as: :new_category
  get 'categories/:id' => 'categories#show', as: :category
  get 'categories/:id/edit' => 'categories#edit', as: :edit_category
  patch 'categories/:id' => 'categories#update'
  delete 'categories/:id' => 'categories#destroy'

  get 'users/:user_id/skills/new' => 'skills#new', as: :new_skill
  get 'users/:user_id/skills/:id' => 'skills#show', as: :skill
  get 'users/:user_id/skills/:id/edit' => 'skills#edit', as: :edit_skill
  patch 'users/:user_id/skills/:id' => 'skills#update'
  delete 'users/:user_id/skills/:id' => 'skills#destroy'

  get 'users/:user_id/messages' => 'messages#index', as: :messages
  get 'users/:user_id/messages/new' => 'messages#new', as: :new_message
  get 'users/:user_id/messages/:id' => 'messages#show', as: :message
  get 'users/:user_id/messages/:id/edit' => 'messages#edit', as: :edit_message
  post 'users/:user_id/messages' => 'messages#create'
  patch 'users/:user_id/messages/:id' => 'messages#update'
  delete 'users/:user_id/messages/:id' => 'messages#destroy'


  get 'users/' => 'users#index'
  post 'users/' => 'users#create'
  get 'users/new' => 'users#new', as: :new_user
  get 'users/:id' => 'users#show', as: :user
  get 'users/:id/edit' => 'users#edit', as: :edit_user
  patch 'users/:id' => 'users#update'
  delete 'users/:id' => 'users#destroy'

  get 'login/' => 'sessions#new'
  post 'login/' => 'sessions#create'
  delete 'logout/' => 'sessions#destroy'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
  has_many :skills
  has_many :users, through: :skills
end

app/models/message.rb
class Message < ApplicationRecord
  belongs_to :to, class_name: 'User'
  belongs_to :from, class_name: 'User'
end

app/models/skill.rb
class Skill < ApplicationRecord
  belongs_to :category
  belongs_to :user, :optional => true
end

app/models/user.rb
class User < ApplicationRecord
  has_secure_password
  has_many :skills, dependent: :destroy
  has_many :categories, through: :skills
  has_many :sent_messages, class_name: 'Message', :foreign_key => 'from_id', dependent: :destroy
  has_many :received_messages, class_name: 'Message', :foreign_key => 'to_id', dependent: :destroy
  accepts_nested_attributes_for :skills, allow_destroy: true, reject_if: :all_blank
  has_attached_file :image, styles: {
    small: "100x100",
    med: "200x200",
    large: "300x300"
  }
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def new
  end

  def show
  end

  def edit
  end
end

app/controllers/messages_controller.rb
class MessagesController < ApplicationController

  def index
    @received_messages = Message.where(to_id: current_user.id)
    @sent_messages = Message.where(from_id: current_user.id)
  end
  def new
    @message = Message.new
  end

  def show
    @message = Message.find(params[:id])
  end

  def edit
  end

  def create
    @message = Message.new(params.require(:message).permit(:content))
    @message.to = User.find(params[:user_id])
    @message.from = current_user
    if @message.save
      redirect_to messages_path(current_user)
    else
      render :new
    end
  end

  def destroy
    @message = Message.find(params[:id])
    if @message.to == current_user || @message.from == current_user
      @message.destroy
      redirect_to messages_path(current_user)
    else
      redirect_to users_path
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new

  end

  def create
    user = User.find_by(email: params[:login][:email])
    if user && user.authenticate(params[:login][:password])
      #set a cookie, so our browser knows we are who we say we are
      session[:user_id] = user.id.to_s
      redirect_to user
    else
      #give them another shot at logging in, perhaps by redirecting back to the login form_for
      render :new
    end
  end


  def destroy
    session.delete(:user_id)
    redirect_to login_path
  end
end

app/controllers/skills_controller.rb
class SkillsController < ApplicationController
  before_action :set_skill, only: [:show, :edit, :update]
  def new
    @skill = Skill.new
  end

  def show
  end

  def edit

  end

  def update
    if @skill.update_attributes(skill_params)
      redirect_to user_path(current_user)
    else
      render :edit
    end
  end

  private
  def skill_params
    params.require(:skill).permit(:price, :description)
  end
  def set_skill
    @skill = Skill.find(session[:user_id])
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]
  def index
    @users = User.all
  end

  def new
    @user = User.new
    @user.skills.build
  end

  def create
    @user = User.new(user_params)

    # store all emails in lowercase to avoid duplicates and case-sentive login errors
    @user.email.downcase!

    if @user.save
      session[:user_id] = @user.id.to_s
      flash[:notice] = "Account created succesfully!"
      redirect_to users_path
    else
      flash.now.alert = "Oops, couldn't create account. Please make sure you are using a valid email and password and try again."
      render :new
    end
  end

  def edit
    @user.skills.build
  end

  def update
    if @user.update_attributes(user_params)
      redirect_to @user
    else
      render :edit
    end
  end
  
  def show

  end

  def destroy
    @user.destroy
    redirect_to users_path
  end
private

  def user_params
    params.require(:user).permit(:name, :description, :dob, :email, :password, :password_confirmation, :image,  skills_attributes:[:id, :category_id, :description, :price, :_destroy])
  end

  def set_user
    @user = User.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper

end

app/helpers/carousel_helper.rb
module CarouselHelper

  def carousel_for(images)
    Carousel.new(self, images).html
  end

  class Carousel
    def initialize(view, images)
      @view, @images = view, images
      @uid = SecureRandom.hex(6)
    end

    def html
      content = view.safe_join([indicators, slides, controls])
      view.content_tag(:div, content, class: 'carousel slide')
    end

    private

    attr_accessor :view, :images, :uid
    delegate :link_to, :content_tag, :image_tag, :safe_join, to: :view

    def indicators
      items = images.count.times.map { |index| indicator_tag(index) }
      content_tag(:ol, safe_join(items), class: 'carousel-indicators')
    end

    def indicator_tag(index)
      options = {
        class: (index.zero? ? 'active' : ''),
        data: {
          target: uid,
          slide_to: index
        }
      }
      content_tag(:li, '', options)
    end

    def slides
      items = images.map.with_index { |image, index| slide_tag(image, index.zero?) }
      content_tag(:div, safe_join(items), class: 'carousel-inner')
    end

    def slide_tag(image, is_active)
      options = {
        class: (is_active ? 'item active' : 'item'),
      }
      content_tag(:div, image_tag(image, class: 'img-responsive'), options)
    end

    def controls
      safe_join([control_tag('left'), control_tag('right')])
    end
    def control_tag(direction)
      options = {
        class: "#{direction} carousel-control",
        data: { slide: direction == 'left' ? 'prev' : 'next' }
      }

      icon = content_tag(:i, '', class: "glyphicon glyphicon-chevron-#{direction}")
      control = link_to(icon, "##{uid}", options)
    end
  end
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/messages_helper.rb
module MessagesHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    @current_user ||= User.find_by(id: session[:user_id])
  end
end

app/helpers/skills_helper.rb
module SkillsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/categories/edit.html.erb
<h1>Categories#edit</h1>
<p>Find me in app/views/categories/edit.html.erb</p>

app/views/categories/new.html.erb
<h1>Categories#new</h1>
<p>Find me in app/views/categories/new.html.erb</p>

app/views/categories/show.html.erb
<h1>Categories#show</h1>
<p>Find me in app/views/categories/show.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LuxChange</title>
    <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
  <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
  <link href="https://fonts.googleapis.com/css?family=Cormorant+Garamond|Merienda+One|PT+Sans+Narrow|Proza+Libre|Sansita+One" rel="stylesheet">
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div id="main-container" class="container-fluid">
      <div class="row">
        <div class="col-xs-5, jumbotron" style="color:rgba(127, 63, 191, 0.8)">
          <h1 id="top_title">LuxChange</h1>
        </div>
        <div class="col-xs-12">
          <%= yield %>
        </div>
      </div>
    </div>

  </body>
</html>

app/views/messages/edit.html.erb
<h1>Messages#edit</h1>
<p>Find me in app/views/messages/edit.html.erb</p>

app/views/messages/index.html.erb
<ul class="nav nav-pills", role="tablist", style="float:right">
  <li class="active, navb"><%= link_to 'Home', users_path, class: 'btn btn-primary' %></li>
  <li class="active, navb"><%= link_to 'Your Profile', user_path(current_user), class: 'btn btn-primary' %></li>
</ul>
<h1 id="messagesTitle"><%= current_user.name %> Messages </h1>
<ul>
    <h3>Received Messages:</h3>
    <% @received_messages.each do |msg|%>
      <li id="eachReceivedMsg">
        <h4 class="msgTitle">Message from <%= msg.from.name %></h4>
        <h5><%= msg.content %></h5> <br>
        <%= link_to 'Delete Message', message_path(msg.to, msg), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-primary' %>
      <% end %>
      </li>

    <h3>Sent Messages:</h3>
    <% @sent_messages.each do |msg|%>
      <li id="eachSentMsg">
        <h4 class="msgTitle">Message to <%= msg.to.name %></h4>
        <h5><%= msg.content %></h5> <br>
        <%= link_to 'Delete Message', message_path(msg.to, msg), method: :delete, data: {confirm: "Are you sure?"}, class: 'btn btn-primary' %>
    <% end %>
    </li>
</ul>

app/views/messages/new.html.erb
<h2>Hello <%= current_user.name %> </h2>

<h1>New Message:</h1>
<%= form_for @message do |f| %>
  <div class='field form-group'>
    <% f.label :message %>
      <%= f.text_area :content, :rows => 5, :cols => 40 %>
    <%= f.submit 'Send', class: 'btn btn-primary' %>
  </div>
<% end %>
<%= link_to 'Home', users_path, class: 'btn btn-primary' %>

app/views/messages/show.html.erb
<h1>Messages#show</h1>
<p>Find me in app/views/messages/show.html.erb</p>

app/views/skills/edit.html.erb
<h1>Skills#edit</h1>
<p>Find me in app/views/skills/edit.html.erb</p>

app/views/skills/index.html.erb
<h1>Skills#index</h1>
<p>Find me in app/views/skills/index.html.erb</p>

app/views/skills/new.html.erb
<h1>Skills#new</h1>
<p>Find me in app/views/skills/new.html.erb</p>

app/views/skills/show.html.erb
<h1>Skills#show</h1>

app/views/users/_form.html.erb
<%= form_for @user do |f| %>
  <div class="field form-group">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field form-group">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field form-group">
    <%= f.label :date_of_birth %>
    <%= f.date_field :dob %>
  </div>

  <div class="field form-group">
    <%= f.label :interests %>
    <%= f.text_field :description %>
  </div>

  <div class="field form-group">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>
  <div class="field form-group">
    <%= f.label :password_confirmation %>
    <%= f.password_field :password_confirmation %>
  </div>
  <div>
    <%= f.label :picture %>
    <%= f.file_field :image%>
  </div> <br>
  <%= f.fields_for :skills do |ff| %>
    <%= render 'skill_fields', f: ff %>
  <% end %>
  <div>
    <%= link_to_add_association 'Add Skill', f, :skills, class: 'label label-default' %>
  </div> <br>
  <div>
    <%= f.submit 'Done', class: 'btn btn-primary' %>
  </div>
<% end %>

app/views/users/_skill_fields.html.erb
  <div>
    <% if f.object.persisted? %>
      <%= f.check_box :_destroy  %>
      <%= f.label :delete %>
    <% end %>
  </div>
  <div class="field form-group">
    <%= f.label :category_id %>
    <%= f.collection_select :category_id, Category.all, :id, :name, include_blank: true %>
  </div>
  <div class="field form-group">
    <%= f.label :describe_skill %>
    <%= f.text_field :description %>
  </div>
  <div class="field form-group">
    <%= f.label :price %>($)
    <%= f.number_field :price %>
  </div>
  

app/views/users/edit.html.erb
<ul class="nav nav-pills", role="tablist", style="float:right">
  <li class="active, navb"><%= link_to 'Home', users_path, class: 'btn btn-primary' %></li>
</ul>

<h1>Edit Profile</h1>
<div class="form">
  <%= render 'form' %>
</div>

app/views/users/index.html.erb
<% if current_user %>
<ul class="nav nav-pills", role="tablist", style="float:right">
  <li class="active, navb"><%= link_to 'Your Profile', user_path(current_user), class: 'btn btn-primary' %></li>
  <li class="active, navb"><%= link_to 'Log Out', logout_path, class: 'btn btn-primary', method: :delete %></li>
</ul>
<h1>Home</h1>
  <h2>Hello <%= current_user.name %>! </h2> <br>
  <div class="picture">
    <%= image_tag current_user.image.url(:med), class: 'img-rounded' %>
  </div>
  <h3>Users</h3> <br>
  <ul>
    <% @users.each do |user| %>
    <li id="eachUser">
      <h4><%= link_to user.name, user_path(user) %></h4> <%= image_tag user.image.url(:small), class: 'img-rounded' %> <br> <strong>INTERESTS</strong> <br>
      <h5><%= user.description %></h5>
      <strong>SKILLS</strong> <br>
      <% user.skills.each do |skill| %>
      <h5>* <%= skill.description %></h5>
      <% end %>
      <%= link_to 'Send Message', new_message_path(user), class: 'btn btn-primary' %>
    </li> <br>
    <% end %>
  </ul>
<% else %>
  <ul class="nav nav-pills", role="tablist", style="float:right">
    <li class="active, navb"><%= link_to 'Log In', login_path, class: 'btn btn-primary' %></li>
    <li class="active, navb"><%= link_to 'Sign Up', new_user_path, class: 'btn btn-primary' %></li>
  </ul>

  <h1 id="welcomeTitle">Welcome</h1>

  <h3>What do we offer?</h3>
  <h5 id="welcomeText">LuxChange is a community where you can find other women like you, with the same interests and/or necessities, where you can share your skills and the best part it's that you can get something in return, without involving any cash!</h5>
  <% @image_urls=["https://static1.squarespace.com/static/5575ed06e4b019b0586d393c/5633f4fee4b0e41cc45eb923/5633f508e4b062bdba18f030/1446245649856/Women+In+Tech+-+92.jpg", "http://wdy.h-cdn.co/assets/cm/15/09/54ebaae1869bb_-_women-cooking-xl.jpg", "http://s1.1zoom.me/big0/352/Fitness_group_of_women_451604.jpg"] %>

  <div id="carousel-example-generic" class="carousel slide" data-ride="carousel">
    <ol class="carousel-indicators">
    <li data-target="#carousel-example-generic" data-slide-to="0" class="active"></li>
    <li data-target="#carousel-example-generic" data-slide-to="1"></li>
    <li data-target="#carousel-example-generic" data-slide-to="2"></li>
  </ol>
    <!-- Wrapper for slides -->
    <div style='margin: auto'>
      <%= carousel_for(@image_urls) %>
    </div>

    <a class="left carousel-control" href="#carousel-example-generic" role="button" data-slide="prev">
    <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
    <span class="sr-only">Previous</span>
  </a>
  <a class="right carousel-control" href="#carousel-example-generic" role="button" data-slide="next">
    <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
    <span class="sr-only">Next</span>
  </a>
  </div>

<% end %>

app/views/users/new.html.erb
<ul class="nav nav-pills", role="tablist", style="float:right">
  <li class="active, navb"><%= link_to 'Home', users_path, class: 'btn btn-primary' %></li>
</ul>
<h1>Sign Up</h1>
  <div class="form">
    <%= render 'form' %>
  </div>

app/views/users/show.html.erb
<ul class="nav nav-pills", role="tablist", style="float:right">

  <li class="active, navb"><%= link_to 'Edit Profile', edit_user_path(@user), class: 'btn btn-primary' if current_user == @user %></li>
  <li class="active, navb"><%= link_to 'Delete Profile', user_path, class: 'btn btn-danger', method: :delete, data: {confirm: "Are you sure you want to delete your profile?"} if current_user == @user %></li>
  <li class="active, navb"><%= link_to 'Home', users_path, class: 'btn btn-primary' %></li>
  <li class="active, navb"><%= link_to 'Send Message', new_message_path(@user), class: 'btn btn-primary' if current_user != @user %></li>
  <li class="active, navb"><%= link_to 'Messages', messages_path(@user), class: 'btn btn-primary' if current_user == @user %></li>
  <li class="active, navb"><%= link_to 'Log Out', logout_path, class: 'btn btn-primary', method: :delete if current_user == @user%></li>
</ul>

<h1>Profile</h1>
<div>
  <h2> <%= @user.name %> </h2>
  <div class="picture">
    <%= image_tag @user.image.url(:large), class: 'img-circle' %>
  </div>
  <ul id="profileView">
    <h3>Description: </h3>
    <h5><%= @user.description %></h5>
    <%# @user.categories.each do |category| %>
    <% Category.all.each do |category| %>
    <% if @user.skills.where(category: category).count > 0 %>
    <h3><%= category.name %>:</h3>
    <% @user.skills.where(category: category).each do |skill| %>
    <li>
      <h5><%= skill.description %></h5>
      <h5>Price: $<%= skill.price %></h5>
    </li>
    <% end %>
    <% end %>
    <% end %>
  </ul>
</div>